# font
font_family 		Hack
bold_font		auto
italic_font		auto
bold_italic_font	auto

font_size 12

# special
foreground       #ffffff
foreground_bold  #ffffff
cursor           #ffffff
background       #000019
background_opacity 0.5

# black
color0   #33195e
color8   #a2979c

# red
color1   #C04755
color9   #BD4A85

# green
color2   #BD40A4
color10  #BD40A4

# yellow
color3   #EBC355
color11  #D0A4B9

# blue
color4   #353AAA
color12  #DBC7A5

# magenta
color5   #B83AAB
color13  #AB95DD

# cyan
color6   #27D5EA
color14  #82A4C6

# white
color7   #DFC2CA
color15  #f8f8f2
