# font
font_family 		Cascadia Code
bold_font		auto
italic_font		auto
bold_italic_font	auto

font_size 12

# special
foreground       #D9C9DE
foreground_bold  #D9C9DE
cursor           #D9C9DE
background       #080810
background_opacity 0.9

# black
color0   #080810
color8   #978C9B

# red
color1   #62609C
color9   #62609C

# green
color2   #5963E5
color10  #5963E5

# yellow
color3   #BC68CD
color11  #BC68CD

# blue
color4   #6589B3
color12  #6589B3

# magenta
color5   #6198E9
color13  #6198E9

# cyan
color6   #9F9AE5
color14  #9F9AE5

# white
color7   #D9C9DE
color15  #D9C9DE
