#!/bin/sh

# Use neovim for vim if present.
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="trash --trash-dir=TRASHDIR" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner"

# Image previews (sort of) in lf
alias \
	lf="lfrun"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	trem="transmission-remote" \
	e="$EDITOR" \
	se="sudoedit" \
	z="zathura" \
	nvd-set="nvidia-settings --config="$XDG_CONFIG_HOME"/nvidia/settings"

alias \
	weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport" \

# Git aliases
alias \
	gau="git add -u" \
	gpsc="git push git@github.com:Kho-Dialga/configs.git" \
	gpss="git push git@github.com:Kho-Dialga/st-dialga.git" \
	gpsd="git push git@github.com:Kho-Dialga/dwm-dialga.git" \
	gpsdm="git push git@github.com:Kho-Dialga/dmenu-dialga.git" \
	gpst="git push git@github.com:Kho-Dialga/touhou-replays.git" \
	gpl="git pull" \
	gcm="git commit -m" \
	gft="git fetch" \
	gbr="git branch" \
	gck="git checkout" \
	gst="git status"
 # Pacman aliases
 alias \
	 psi="sudo pacman -S" \
	 pss="pacman -Ss" \
	 psu="sudo pacman -Syu" \
	 prm="sudo pacman -Rns" \
	 pro="sudo pacman -Qttdq | sudo pacman -Rns - " \
	 pqa="pacman -Q" \
	 pqs="pacman -Qs" \
	 pqe="pacman -Qqe" \
	 pqo="pacman -Qtdq" \
	 ysi="yay -S" \
	 yss="yay -Ss" \
	 ysu="yay -Syu"
# Portage aliases
alias \
	emi="sudo emerge -a" \
	emr="sudo emerge --depclean" \
	ems="emerge -s" \
	emp="emerge -pv" \
	emq="eix -I" \
	emu="sudo emerge -uavDN @world" \
	eeu="sudo dispatch-conf"
