#!/bin/sh
eval $(dbus-launch --sh-syntax --exit-with-x11)		# Ensures dbus is launched along witn the X session.
sxhkd &							# Creates the keyboard shortcuts.
picom --experimental-backends &				# Launches picom for transparency.
mpd &							# Launches mpd for using alongside ncmpcpp.
xset r rate 300 50 &					# Speeds up the xrate.
dunst &							# Launches dunst for notifications.
setbg ~/pix/wallpaper &					# Sets the wallpaper, change the directory to the path to your image.
redshift &						# Launches redshift for adjusting the color temperature.
xrdb ~/.config/Xresources &				# Reloads the Xresources file.
mw -Y & 						# Syncs all mailboxes.
dwmblocks &						# Start the statusbar
udiskie	&						# Automounts USBs
newsup &						# Updates RSS feeds
mkfifo /tmp/xobpulse &					# Makes xob work
tail -f /tmp/xobpulse | xob &				# Starts xob for a pulseaudio volume bar.
