#! /bin/sh

bspc config focus_follows_pointer false

# Auto start

killall sxhkd; while pgrep -u $UID -x sxhkd >/dev/null; do sleep 1; done; sxhkd -c ~/.config/sxhkd/sxhkdrc-bsp &
polylaunch &
pgrep bspswallow || bspswallow &

# Workspaces

bspc monitor -d 1 2 3 4 5 6 7 8 9

# Layout configuration

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Colors

xresource() {
  xrdb -query | grep -E "^(bspwm|\*)\.$1" | sed -r "s/^[^:]+:\s+//" | tail -n 1
}

bspc config normal_border_color		      $(xresource color4)
bspc config active_border_color	          $(xresource color6)
bspc config focused_border_color	      $(xresource color9)
bspc config presel_feedback_color	      $(xresource color5)
bspc config urgent_border_color 	      $(xresource color3)

# Window rules

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
